server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: tfg-gateway
  cloud:
    config:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=1
        - id: exam-service
          uri: lb://EXAM-SERVICE
          predicates:
            - Path=/tests/**
          filters:
            - StripPrefix=1
        - id: classroom-service
          uri: lb://CLASSROOM-SERVICE
          predicates:
            - Path=/classrooms/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
    register-with-eureka: true
  instance:
    prefer-ip-address: false
    hostname: ${SERVICE_IP:localhost}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    com.netflix.discovery: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG
